<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\ComponentViewModel;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var ComponentViewModel $viewModel */
/** @var ComponentUtil $componentUtil */
$htmlId = $componentUtil->getElementIdByBlock($block);
// @todo: Why is data-source is added in the HTML tree? By Hyva?
?>
<form x-target="<?= $viewModel->getTargetString() ?>" id="<?= $htmlId ?>" method="post" action="<?= $componentUtil->getPostUrl(); ?>" class="my-4">
    <?= $block->getChildHtml() ?>
    <input type="hidden" name="handles" value="<?= $componentUtil->getHandles($block) ?>"/>
    <input type="hidden" name="block" value="<?= $block->getNameInLayout() ?>"/>
    <?= $block->getBlockHtml('formkey') ?>
</form>
