<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Config\Config;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var Config $config */
/** @var ComponentUtil $componentUtil */

$config = $viewModelFactory->create(Config::class);
$componentUtil = $viewModelFactory->create(ComponentUtil::class);
?>
<script>
    const LokiComponentFormKey = '<?= $componentUtil->getFormKey() ?>';

    const LokiComponentType = {
        id: '',
        name: '',
        elementId: '',
        blockId: '',
        field: null, // @todo: Move to LokiFieldComponentType
        fieldValue: null, // @todo: Move to LokiFieldComponentType
        targets: [],
        messages: [],
        value: null, // @todo: Move to LokiFieldComponentType
        visible: false,
        lazyLoad: false,
        beforePostValue: null,
        autofillListenerTimer: null,
        initActions: {
            loadInitialData() {
                const jsonData = JSON.parse(this.$root.getAttribute('x-init-data'));
                for ([key, value] of Object.entries(jsonData)) {
                    this[key] = value;
                }

                this.field = this.$root.querySelectorAll('[data-type="field"]')[0];
            },
            register() {
                Alpine.store('components').add(this);
            },
            setValidation() {
                if (!this.field) {
                    return;
                }

                if (true === this.valid) {
                    this.field.removeAttribute('aria-invalid');
                } else {
                    this.field.setAttribute('aria-invalid', true);
                }

                this.$watch('valid', () => {
                    if (true === this.valid) {
                        this.field.removeAttribute('aria-invalid');
                    } else {
                        this.field.setAttribute('aria-invalid', true);
                    }
                })
            },
            listenToAutofillChanges() {
                if (!this.field || this.field.disabled) {
                    return;
                }

                this.fieldValue = this.field.value;
                this.autofillListenerTimer = setInterval((function () {
                    if (!this.field.value || this.field.value === this.fieldValue || this.field.value === this.value) {
                        return;
                    }

                    if (document.activeElement && document.activeElement.id === this.field.id) {
                        return;
                    }

                    this.fieldValue = this.field.value;
                    this.value = this.field.value;
                    this.field.dispatchEvent(new Event('change')); // @todo: What should this do?
                }).bind(this), 2000);
            },
            lazyLoad() {
                if (this.lazyLoad) {
                    this.post({});
                }
            }
        },
        beforeInit() {
        },
        async init() {
            this.beforeInit();

            for ([key, callback] of Object.entries(this.initActions)) {
                await callback.apply(this);
            }

            this.afterInit();
        },
        afterInit() {
        },
        async post(value) {
            if (value instanceof Event) {
                value = null;
            }

            if (!value) {
                value = this.value;
            }

            if (this.field) {
                this.field.setAttribute('aria-busy', true);
                this.field.setAttribute('disabled', true);
            }

            this.targets.forEach(target => {
                const targetElement = document.getElementById(target);
                if (targetElement) {
                    targetElement.setAttribute('aria-busy', true);
                } else {
                    <?php if ($config->isDebug()): ?>
                    LokiComponentsLogger.warning('Target element "' + target + '" does not exist');
                    <?php endif; ?>
                }
            });

            this.beforePostValue = this.value;
            await fetch('<?= $componentUtil->getPostUrl() ?>?form_key=' + LokiComponentFormKey + '&isAjax=true', {
                method: 'POST',
                mode: 'same-origin',
                headers: {
                    'X-Alpine-Request': true,
                    'X-Requested-With': 'XMLHttpRequest',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    targets: this.targets,
                    componentData: value,
                    block: this.blockId,
                    handles: <?= json_encode($componentUtil->getHandles($block)) ?>,
                    request: <?= json_encode($componentUtil->getRequestParams()) ?>,
                })
            })
                .then(response => {
                    if (response.ok) {
                        return response.text()
                    }

                    LokiComponentsLogger.error('Fetch error', response);
                    throw new Error(response.statusText);
                })
                .then(html => {
                    try {
                        const data = JSON.parse(html);
                        if (data) {
                            this.handleJson(data);
                            return;
                        }
                    } catch (e) {
                    }

                    const parser = new DOMParser();
                    const ajaxDocument = parser.parseFromString(html, "text/html");
                    this.targets.forEach(target => {
                        if (target === this.elementId) {
                            return;
                        }

                        const targetElement = document.getElementById(target);
                        const newTargetElement = ajaxDocument.getElementById(target);

                        if (!targetElement || !newTargetElement) {
                            return;
                        }

                        const targetComponent = Alpine.store('components').getComponentByElementId(target);
                        if (targetComponent) {
                            targetComponent.destroy();
                        }

                        targetElement.outerHTML = newTargetElement.outerHTML;
                    });

                    const newTargetElement = ajaxDocument.getElementById(this.elementId);
                    if (!newTargetElement) {
                        return;
                    }

                    const targetElement = document.getElementById(this.elementId);
                    this.destroy();

                    targetElement.innerHTML = newTargetElement.innerHTML;
                    targetElement.setAttribute('x-init-data', newTargetElement.getAttribute('x-init-data'));

                    const jsonData = JSON.parse(targetElement.getAttribute('x-init-data'));
                    for ([key, value] of Object.entries(jsonData)) {
                        this[key] = value;
                    }

                    if (!this.valid) {
                        this.value = this.beforePostValue;
                    }

                    this.$nextTick(() => {
                        document.dispatchEvent(new CustomEvent('loki-components.component.update', {detail: {component: this}}));

                        if (document.lastFocusElementId) {
                            document.getElementById(document.lastFocusElementId).focus();
                        }
                    });
                })
                .catch(error => {
                    this.addGlobalMessage('error', error);
                })
                .finally(() => {
                    this.$nextTick(() => {
                        this.targets.forEach(target => {
                            const targetElement = document.getElementById(target);
                            if (targetElement) {
                                targetElement.removeAttribute('aria-busy');
                            } else {
                                LokiComponentsLogger.error('Target not found', target);
                            }
                        });
                    });

                    if (this.field) {
                        this.field.removeAttribute('aria-busy');
                        this.field.removeAttribute('disabled');
                    }

                    LokiComponentsFocusListener();
                });
        },
        handleJson(data) {
            if (data.error) {
                LokiComponentsLogger.error(data.error);
                this.addGlobalMessage('error', data.error);
            }

            if (data.redirect) {
                console.log('Redirecting to ' + data.redirect);
                document.location.assign(data.redirect);
                //window.location.replace(data.redirect);
            }
        },
        getDetailsString() {
            return JSON.stringify(this.getDetails());
        },
        getDetails() {
            return {
                value: this.value,
                visible: this.visible,
                valid: this.valid,
            };
        },
        addGlobalMessage(messageType, messageText) {
            const globalMessageComponent = Alpine.store('components').get('LokiComponentsGlobalMessages');
            globalMessageComponent.messages.push({
                type: messageType,
                text: messageText
            });
        },
        destroyActions: {
            clearAutofillListenerTimer() {
                clearInterval(this.autofillListenerTimer);
            }
        },
        async destroy() {
            for ([key, callback] of Object.entries(this.destroyActions)) {
                await callback.apply(this);
            }
        }
    }
</script>
