<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
$componentUtil = $viewModelFactory->create(ComponentUtil::class);
?>
<script>
    const LokiComponentType = {
        title: '',
        name: '',
        elementId: '',
        blockId: '',
        target: '',
        value: null,
        initActions: {
            loadInitialData: function () {
                const jsonData = JSON.parse(this.$el.getAttribute('x-init-data'));
                for ([key, value] of Object.entries(jsonData)) {
                    this[key] = value;
                }
            }
        },
        beforeInit() {
        },
        init() {
            this.beforeInit();

            for ([key, callback] of Object.entries(this.initActions)) {
                callback.apply(this);
            }

            this.afterInit();
        },
        afterInit() {
        },
        post(data) {
            if (!data) {
                data = this.value;
            }

            console.log('AJAX call', this.id, data, this.target);
            this.$ajax('<?= $componentUtil->getPostUrl() ?>', {
                method: 'post',
                target: this.target,
                sync: true,
                body: {
                    json: JSON.stringify(data),
                    block: this.blockId,
                    handles: '<?= $componentUtil->getHandles($block) ?>',
                    form_key: hyva.getFormKey()
                }
            });
        },
        afterAjax(event) {
            // @todo: This requires @ajax:success or something to be added to the element
            this.$root.removeAttribute('aria-busy');
            console.log('ajax:after', event);
        }
    }
</script>
