<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
$componentUtil = $viewModelFactory->create(ComponentUtil::class);
?>
<script>
    const LokiComponentType = {
        value: null,
        loading: false,
        initActions: {
            loadInitialData: function() {
                const jsonData = JSON.parse(this.$el.getAttribute('x-init-data'));
                for ([key, value] of Object.entries(jsonData)) {
                    this[key] = value;
                }
            }
        },
        beforeInit() {
        },
        init() {
            this.beforeInit();

            for ([key, callback] of Object.entries(this.initActions)) {
                callback.apply(this);
            }

            this.afterInit();
        },
        afterInit() {
        },
        getPostData() {
            return this.value;
        },
        async post() {
            this.loading = true;
            await this.$ajax('<?= $componentUtil->getPostUrl() ?>', {
                method: 'post',
                target: this.target,
                sync: true,
                body: {
                    json: JSON.stringify(this.getPostData()),
                    block: this.blockId,
                    handles: '<?= $componentUtil->getHandles($block) ?>',
                    form_key: hyva.getFormKey()
                }
            });
            this.loading = false;
        }
    }
</script>
