<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
$componentUtil = $viewModelFactory->create(ComponentUtil::class);
?>
<script>
    const LokiComponentType = {
        loading: false,
        async post(data) {
            this.loading = true;
            await this.$ajax('<?= $componentUtil->getPostUrl() ?>', {
                method: 'post',
                target: this.target,
                sync: true,
                body: {
                    json: JSON.stringify(data),
                    block: this.blockId,
                    handles: '<?= $componentUtil->getHandles($block) ?>',
                    form_key: hyva.getFormKey()
                }
            });
            this.loading = false;
        }
    }
</script>
