<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 2.1.3 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiComponentsGlobalMessages', () => ({
            init() {
                const messages = JSON.parse(this.$root.getAttribute('data-messages'));
                messages.forEach(message => {
                    message.text = decodeURIComponent(message.text.replace(/\+/g, ' '));
                    Alpine.store('LokiMessageStore').addMessage(message.type, message.text);
                });
            },
        }));
    });
</script>
