<?php
declare(strict_types=1);

/** @version 2.1.0 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiModal', () => ({
            ...LokiLoadInitMethodsComponentPartial,
            ...LokiModalComponentPartial,
            async init() {
                this.loadInitMethods();
            },
        }));
    });
</script>
