<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiModal', () => ({
            async init() {
                const initMethods = Object.getOwnPropertyNames(this).filter((methodName) => {
                    return methodName.startsWith('init') && methodName !== 'init';
                });

                initMethods.forEach(methodName => {
                    this[methodName].apply(this);
                })
            },
            ...LokiModalComponentPartial
        }));
    });
</script>
