<?php
declare(strict_types=1);

/** @version 2.2.35 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiComponentToggle', () => ({
            ...LokiComponentType,
            toggle() {
                this.value = !this.value;
                this.post();
            }
        }));
    });
</script>
