<?php
declare(strict_types=1);

/** @version 2.2.36 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiToggle', () => ({
            shown: false,
            hidden() {
                return !this.shown;
            },
            toggle() {
                this.shown = !this.shown;
            }
        }));
    });
</script>
