<script>
    const LokiComponentsStorage = {
        get() {
            const lokiComponentsJson = localStorage.getItem('loki-components');
            if (!lokiComponentsJson) {
                return {};
            }

            return JSON.parse(lokiComponentsJson);
        },
        load(key) {
            const data = this.get();
            return data[key];
        },
        save(key, value) {
            const data = this.get();
            data[key] = value;
            const lokiComponentsJson = JSON.stringify(data);
            localStorage.setItem('loki-components', lokiComponentsJson);
        }
    }
</script>
