<?php
declare(strict_types=1);

/** @version 2.2.28 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiLoadDataComponentPartial = {
        loadData() {
            const initialData = this.$refs.initialData;
            if (!initialData) {
                return;
            }

            const jsonData = JSON.parse(initialData.innerText);
            if (!jsonData) {
                console.log('Failed to read initial data for Loki Component', this.$root);
                return;
            }

            for ([key, value] of Object.entries(jsonData)) {
                this[key] = value;
            }
        },
    };
</script>
