<?php
declare(strict_types=1);

/** @version 2.2.4 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiLoadDestroyMethodsComponentPartial = {
        loadDestroyMethods() {
            const destroyMethods = Object.getOwnPropertyNames(this).filter((methodName) => {
                return methodName.startsWith('destroy') && methodName !== 'destroy';
            });

            destroyMethods.forEach(methodName => {
                this[methodName].apply(this);
            });
        },
    };
</script>
