<?php
declare(strict_types=1);

/** @version 2.0.15 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiLoadInitMethodsComponentPartial = {
        loadInitMethods() {
            const initMethods = Object.getOwnPropertyNames(this).filter((methodName) => {
                return methodName.startsWith('init') && methodName !== 'init';
            });

            initMethods.forEach(methodName => {
                this[methodName].apply(this);
            });
        },
    };
</script>
