<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 2.2.35 */
/** @var Template $block */

$showLoaderTimeout = (int) $block->getShowLoaderTimeout();
if (false === $showLoaderTimeout > 0) {
    $showLoaderTimeout = 400;
}
?>
<script>
    const LokiLoaderComponentPartial = {
        loading: false,
        showLoader: false,
        showLoaderTimeout: <?= (int)$showLoaderTimeout ?>,
        setLoadingStateToElement(elementId, loadingState) {
            const element = document.getElementById(elementId);
            if (!element) {
                return;
            }

            if (loadingState) {
                element.setAttribute('aria-busy', true);
            } else {
                element.removeAttribute('aria-busy');
            }

            const component = Alpine.store('LokiComponents').getComponentByElementId(elementId);
            if (component) {
                component.loading = loadingState;
            }
        }
    };
</script>
