<script>
    const LokiModalComponentPartial = {
        initModalClosing() {
            const modal =this.$refs.modal;
            modal.addEventListener('click', function(event) {
                if (event.target === modal) {
                    modal.close();
                }
            });
        },
        toggleModal() {
            if (this.isModalOpen()) {
                this.$refs.modal.close();
                return;
            }

            this.$refs.modal.showModal();
        },
        isModalOpen() {
            return this.$refs.modal.open;
        },
        isModalClosed() {
            return !this.isModalOpen();
        }
    };
</script>
