<?php
declare(strict_types=1);

/** @version 2.2.27 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiTabComponentPartial = {
        activeTabId: '',
        activeTabClass: 'tab-active',
        inactiveTabClass: 'tab-inactive',
        showActiveTab() {
            this.toggleTab(this.activeTabId);
        },
        setTabInactive(tab) {
            tab.classList.remove(this.activeTabClass);
            tab.classList.add(this.inactiveTabClass);
            tab.setAttribute('aria-selected', 'false');
        },
        setTabActive(tab) {
            tab.classList.remove(this.inactiveTabClass);
            tab.classList.add(this.activeTabClass);
            tab.setAttribute('aria-selected', 'true');
        },
        toggleTab(tabId) {
            this.$root.querySelectorAll('[data-tab-id]').forEach(tab => {
                this.setTabInactive(tab);
            });

            this.$root.querySelectorAll('[data-tab-content]').forEach(tabContent => {
                tabContent.classList.remove('block');
                tabContent.classList.add('hidden');
            });

            const activeTab = this.$root.querySelector('[data-tab-id="' + tabId + '"]');
            if (activeTab) {
                this.setTabActive(activeTab);
            }
            // @todo: Save active tab in session

            const activeContent = this.$root.querySelector('[data-tab-content="' + tabId + '"]');
            if (activeContent) {
                activeContent.classList.remove('hidden');
                activeContent.classList.add('block');
            }

            this.activeTabId = tabId;
        },
        toggleTabs(event) {
            if (!event || !event.target) {
                return;
            }

            const tabId = event.target.getAttribute('data-tab-id');
            if (!tabId) {
                console.error('No tab ID found');
                return;
            }

            this.toggleTab(tabId);
        }
    };
</script>
