<?php
declare(strict_types=1);

/** @version 2.2.6 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiTabComponentPartial = {
        activeTabId: '',
        activeTabClass: 'tab-active',
        inactiveTabClass: 'tab-inactive',
        showActiveTab() {
            this.toggleTab(this.activeTabId);
        },
        toggleTab(tabId) {
            this.$root.querySelectorAll('[data-tab-id]').forEach(tab => {
                tab.classList.remove('tab-active');
                tab.classList.add('tab-inactive');
            });

            this.$root.querySelectorAll('[data-tab-content]').forEach(tabContent => {
                tabContent.classList.remove('block');
                tabContent.classList.add('hidden');
            });

            const activeTab = this.$root.querySelector('[data-tab-id="' + tabId + '"]');
            if (activeTab) {
                activeTab.classList.remove('tab-inactive');
                activeTab.classList.add('tab-active');
            }
            // @todo: Save active tab in session

            const activeContent = this.$root.querySelector('[data-tab-content="' + tabId + '"]');
            if (activeContent) {
                activeContent.classList.remove('hidden');
                activeContent.classList.add('block');
            }
        },
        toggleTabs(event) {
            if (!event || !event.target) {
                return;
            }

            const tabId = event.target.getAttribute('data-tab-id');
            if (!tabId) {
                console.error('No tab ID found');
                return;
            }
            this.toggleTab(tabId);
        }
    };
</script>
