<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\Debugger\DebuggerViewModel;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var DebuggerViewModel $viewModel */
/** @var ComponentUtil $componentUtil */

$htmlId = $componentUtil->getElementIdByBlockName($block->getNameInLayout());
?>
<div id="<?= $htmlId ?>" class="p-4" x-sync>
    <h3 class="text-xl my-4">LokiComponents Debugger</h3>
    <pre><?php var_dump($viewModel->getData()) ?></pre>
</div>

