<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\GlobalMessages\GlobalMessagesViewModel;

/** @var Template $block */
/** @var GlobalMessagesViewModel $viewModel */

?>
<div class="m-4">
    <template x-for="message in messages">
        <div class="message" :class="message.type">
            <span x-html="message.text"></span>
            <button
                type="button"
                class="text-gray-600 hover:text-black"
                aria-label="<?= __('Close message') ?>" @click.prevent="remove(message.text)">
                x
            </button>
        </div>
    </template>
</div>
