<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\Messages\MessagesViewModel;

/** @var Template $block */
/** @var MessagesViewModel $viewModel */

?>
<div>
    <template x-for="message in messages">
        <div class="message" :class="message.type" x-transition>
            <span x-html="message.text"></span>
            <button
                type="button"
                class="text-gray-600 hover:text-black"
                aria-label="<?= __('Close message') ?>" @click.prevent="removeMessage(message.text)">
                x
            </button>
        </div>
    </template>
</div>
