<?php
declare(strict_types=1);

use Loki\Components\Util\Block\ChildRenderer;
use Magento\Framework\Escaper;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;

/** @version 2.2.32 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ChildRenderer $childRenderer */
/** @var CssClass $css */
?>
<div class="<?= $escaper->escapeHtml($css('')) ?>">
    <?= /* @noEscape */ $childRenderer->all($block); ?>
</div>
