<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\Components\Util\Block\CssClass;

/** @var Template $block */
/** @var CssClass $css */
?>
<template x-if="hasLocalMessages">
    <ul
        class="loki-components-messages <?= $css('') ?>"
        aria-errormessage="<?= $block->getAncestorBlock()->getId() ?>">
        <template x-for="message in messages">
            <li :class="message.type" x-html="message.text"></li>
        </template>
    </ul>
</template>
