<?php declare(strict_types=1);

/** @version 2.2.1 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\CssUtils\Util\CssClass;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */
?>
<template x-if="hasLocalMessages">
    <ul
        class="loki-components-messages <?= $escaper->escapeHtmlAttr($css('')) ?>"
        id="<?= $escaper->escapeHtml($block->getDomId()) ?>">
        <template x-for="message in messages">
            <li :class="message.type" x-html="message.text"></li>
        </template>
    </ul>
</template>
