<?php declare(strict_types=1);

/** @version 2.2.18 */

use Loki\Components\Factory\ViewModelFactory;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
?>
<div aria-hidden="true" style="display:none; visibility: hidden;">
    <!-- Not rendered: <?= $escaper->escapeHtml($block->getNameInLayout()) ?> -->
</div>
