<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiComponentGlobalMessages', () => ({
            ...LokiComponentType,
            initActions: {
                ...LokiComponentType.initActions,
                clearAfterTimeout() {
                    if (this.timeout > 0) {
                        setTimeout(() => {
                            this.messages = [];
                        }, this.timeout);
                    }
                }
            },
            remove() {
                this.messages = [];
            }
        }));
    });
</script>
