<?php declare(strict_types=1);

/** @version 2.1.0 */

use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\GlobalMessages\GlobalMessagesViewModel;
use Loki\CssUtils\Util\CssClass;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var GlobalMessagesViewModel $viewModel */
/** @var CssClass $css */
/** @var ViewModelFactory $viewModelFactory */
/** @var ImageOutput $imageOutput */

$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div
    class="<?= /* @noEscape */ $css('fixed z-[300] w-full p-4') ?>"
    x-cloak x-show="hasMessages">
    <template x-for="message in messages">
        <div
            class="<?= /* @noEscape */ $css('message', 'message') ?>"
            :class="message.type">
            <div
                class="<?= /* @noEscape */ $css('inline-block', 'message-text') ?>"
                x-html="message.text"
            ></div>
            <button
                type="button"
                class="<?= /* @noEscape */ $css('text-gray-600 hover:text-black w-3', 'button') ?>"
                aria-label="<?= $escaper->escapeHtml(__('Close message')) ?>"
                :data-message="message.text"
                @click.prevent="removeMessage"
            ><?= /** @noEscape */ $imageOutput->get('Loki_Components::images/xmark.svg') ?></button>
        </div>
    </template>
</div>
