<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\GlobalMessages\GlobalMessagesViewModel;
use Yireo\LokiComponents\Util\Block\CssClass;

/** @var Template $block */
/** @var GlobalMessagesViewModel $viewModel */
/** @var CssClass $css */
?>
<div class="<?= $css('fixed z-40 w-full p-4') ?>" x-cloak x-show="hasMessages">
    <template x-for="message in messages">
        <div class="message" :class="message.type">
            <span x-html="message.text"></span>
            <button
                type="button"
                class="<?= $css('text-gray-600 hover:text-black', 'button') ?>"
                aria-label="<?= __('Close message') ?>"
                :data-message="message.text"
                @click.prevent="removeMessage">
                x
            </button>
        </div>
    </template>
</div>
