<?php declare(strict_types=1);

use Loki\Base\ViewModel\ModuleConfig;
use Loki\Components\Util\Block\ChildRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 2.2.32 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ChildRenderer $childRenderer */
/** @var ModuleConfig $moduleConfig */

if ($block->getLayout()->getBlock('alpine-js.loader')) {
    return;
}
?>
<?= /* @noEscape */ $childRenderer->all($block) ?>
<script defer src="<?= $escaper->escapeUrl($block->getViewFileUrl("Loki_Components::js/alpine.min.js")) ?>"></script>

