<?php
declare(strict_types=1);


use Loki\Components\Util\Block\ChildRenderer;
use Magento\Framework\View\Element\Template;

/** @version 2.6.1 */
/** @var Template $block */
/** @var ChildRenderer $childRenderer */

?>
<script>
    const LokiComponentExtender = {
        extensions: {},
        add(extensionId, extenderFunction) {
            this.extensions[extensionId] = extenderFunction;
        },
        addMixin(extensionId, matchComponentName, mixin) {
            this.extensions[extensionId] = (componentName) => {
                if (matchComponentName === componentName) {
                    return mixin;
                }

                return {};
            };
        }
    };
</script>

<?= /* @noEscape */ $childRenderer->all($block) ?>

<script>
    document.addEventListener('alpine:init', () => {
        const originalAlpineData = Alpine.data;

        Alpine.data = (componentName, componentFactory) => {
            let mixinData = {};
            Object.values(LokiComponentExtender.extensions).forEach(extenderFunction => {
                const currentMixinData = extenderFunction(componentName);
                if (typeof currentMixinData !== 'object') {
                    return;
                }

                mixinData = Object.assign(mixinData, currentMixinData);
            });

            let componentData;
            if (Object.values(mixinData).length > 0) {
                const wrapped = (...args) => {
                    const base = componentFactory(...args);
                    return Object.assign({}, base, mixinData);
                };

                componentData = originalAlpineData(componentName, wrapped);
            } else {
                componentData = originalAlpineData(componentName, componentFactory);
            }

            return componentData;
        };
    });
</script>

