<?php
declare(strict_types=1);

use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\ComponentUtil;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 2.4.1 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentUtil $componentUtil */

$componentUtil = $viewModelFactory->create(ComponentUtil::class);
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.store('LokiComponents', {
            formKey: '<?= $escaper->escapeJs($componentUtil->getFormKey()) ?>',
            components: {},
            getComponentIds() {
                return Object.keys(this.components);
            },
            getComponents() {
                return this.components;
            },
            getComponentArray() {
                return Object.values(this.components);
            },
            add(component) {
                if (!component.id) {
                    component.id = 'unknown';
                }

                this.components[component.id] = component;
                document.dispatchEvent(new CustomEvent(
                    'loki-components.component-register',
                    {detail: {component}}
                ));
            },
            get(componentId) {
                if (this.components[componentId]) {
                    return this.components[componentId];
                }

                throw new Error('No such a component: ' + componentId);
            },
            getComponentByElementId(elementId) {
                return this.getComponentArray().find((component) => {
                    return component.elementId === elementId;
                });
            },
            getComponentByBlockId(blockId) {
                return this.getComponentArray().find((component) => {
                    return component.blockId === blockId;
                });
            },
            exists(component) {
                return document.getElementById(component.elementId);
            },
            removeInvisibleComponents() {
                this.getComponentArray().forEach((component) => {
                    if(!this.exists(component)) {
                        delete this.components[component.id];
                    }
                });
            }
        })
    });
</script>
