<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiComponentsFocusListener = () => {
        return;
        [
            ...document.getElementsByTagName('input'),
            ...document.getElementsByTagName('select'),
            ...document.getElementsByTagName('textarea'),
        ].forEach(function (element) {
            element.addEventListener('focus', (event) => {
                if (event.target.id) {
                    document.lastFocusElementId = event.target.id;
                }
            });
        });
    }

    LokiComponentsFocusListener();
</script>
