<?php declare(strict_types=1);

/** @version 2.1.2 */

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Messages\GlobalMessageRegistry;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var GlobalMessageRegistry $globalMessageRegistry */
/** @var ViewModelFactory $viewModelFactory */
/** @var Escaper $escaper */
$globalMessageRegistry = $viewModelFactory->create(
    GlobalMessageRegistry::class
);
?>
<div id="loki-components-utils-global-message-container"
     data-messages='<?= $escaper->escapeHtml(
         json_encode($globalMessageRegistry->toArray())
     ) ?>'
></div>
