<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Messages\GlobalMessageRegistry;
use Magento\Framework\Escaper;

/** @version 2.1.2 */
/** @var Template $block */
/** @var GlobalMessageRegistry $globalMessageRegistry */
/** @var ViewModelFactory $viewModelFactory */
/** @var Escaper $escaper */

$globalMessageRegistry = $viewModelFactory->create(GlobalMessageRegistry::class);
?>
<div data-messages='<?= $escaper->escapeHtml(json_encode($globalMessageRegistry->toArray())) ?>'>
</div>
