<?php
declare(strict_types=1);

use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Messages\GlobalMessageRegistry;

/**
 * @var GlobalMessageRegistry $globalMessageRegistry
 * @var ViewModelFactory $viewModelFactory
 */
$globalMessageRegistry = $viewModelFactory->create(GlobalMessageRegistry::class);
?>

<div id="loki-components-utils-global-message-container" data-messages='<?= json_encode($globalMessageRegistry->toArray()) ?>'></div>
