<?php
declare(strict_types=1);

/** @version 2.0.14 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiComponentsStorage = {
        get() {
            const lokiComponentsJson = localStorage.getItem('loki-components');
            if (!lokiComponentsJson) {
                return {};
            }

            return JSON.parse(lokiComponentsJson);
        },
        load(key) {
            const data = this.get();
            return data[key];
        },
        save(key, value) {
            const data = this.get();
            data[key] = value;
            const lokiComponentsJson = JSON.stringify(data);
            localStorage.setItem('loki-components', lokiComponentsJson);
        }
    }
</script>
