<?php declare(strict_types=1);

/** @version 2.2.33 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
use Loki\Components\Config\Config;
use Loki\Components\Factory\ViewModelFactory;

/**
 * @var ViewModelFactory $viewModelFactory * @var Config $config
 */
$config = $viewModelFactory->create(Config::class);
?>
<script>
    const LokiComponentsLogger = {
        allowDebugging: <?= $config->isDebug() ? 'true' : 'false' ?>,
        prefix: 'Loki_Components',
        getColor(logType) {
            if (logType === 'notice') {
                return '#6495ED';
            }

            if (logType === 'success') {
                return 'green';
            }

            if (logType === 'warning') {
                return 'orange';
            }

            if (logType === 'error') {
                return 'red';
            }

            return 'gray';
        },
        notice(...args) {
            return this.message('notice', ...args);
        },
        success(...args) {
            return this.message('success', ...args);
        },
        warning(...args) {
            return this.message('warning', ...args);
        },
        error(...args) {
            return this.message('error', ...args);
        },
        debug(...args) {
            if (!this.allowDebugging) {
                return;
            }

            return this.message('debug', ...args);
        },
        message(messageType, ...args) {
            const color = this.getColor(messageType);
            const prefix = this.prefix + ' [' + messageType.toUpperCase() + ']';
            const css = 'color:white; background-color:' + color + '; padding:1px;'
            console.log('%c' + prefix, css, ...args);
        }
    };
</script>
