<?php declare(strict_types=1);

use Loki\Components\Util\Block\CssClass;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var ViewModelFactory $viewModelFactory */
/** @var ImageOutput $imageOutput */
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<button
    aria-label="<?= $escaper->escapeHtml(__('Close')) ?>"
    @click="toggleModal"
    class="<?= /* @noEscape */
    $css('float-right m-4 cursor-pointer w-4') ?>"
><?= /** @noEscape */ $imageOutput->get('Loki_Components::images/xmark.svg') ?></button>
