<?php declare(strict_types=1);

/** @version 2.2.4 */

use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var ViewModelFactory $viewModelFactory */
/** @var ImageRenderer $imageRenderer */

?>
<button
    aria-label="<?= $escaper->escapeHtml(__('Close')) ?>"
    @click.prevent="toggleModal"
    class="<?= $escaper->escapeHtmlAttr($css('float-right cursor-pointer')) ?>"
><?= $escaper->escapeHtml($imageRenderer->icon($block, 'xmark')) ?></button>
